@startuml
skinparam shadowing false
skinparam activity {
  BackgroundColor #DAE8FC
  BorderColor #6C8EBF
}

title UML: активность оформления заказа поставщику

start
:Пользователь выбирает\nпоставщика;
:Система загружает товары,\nсвязанные с поставщиком;

if (Есть товары\nдля заказа?) then (да)
  :Создать черновик заказа;
else (нет)
  :Показать сообщение\nоб отсутствии товаров;
  stop
endif

repeat
  :Пользователь выбирает товар;
  :Пользователь вводит\nзаказываемое количество;

  if (Количество > 0?) then (да)
    :Добавить позицию\nв заказ;
  else (нет)
    :Показать ошибку\nколичества;
  endif
repeat while (Добавить еще позицию?) is (да)

if (В заказе есть\nхотя бы одна позиция?) then (да)
  :Система проверяет,\nчто все товары относятся\nк выбранному поставщику;
  if (Проверка успешна?) then (да)
    :Сохранить заказ;
    :Передать заказ поставщику;
    :Установить статус\n"отправлен поставщику";
  else (нет)
    :Показать список\nошибочных позиций;
    stop
  endif
else (нет)
  :Отменить пустой заказ;
  stop
endif

stop
@enduml
